name: HITWShitpost
version: 1.0
main: io.github.thatsmusic99.hitwshitpost.HITWShitpost
api-version: 1.20

permissions:
  hitw.admin:
    default: op

commands:
  trap:
    description: Instantly activate a random trap.
  keepbag:
    description: Allows players to keep their inventory on death