name: HITWShitpost
version: 2.0
main: io.github.thatsmusic99.hitwshitpost.HITWShitpost
api-version: 26.1.2
depend: [WorldGuard]

permissions:
  hitw.admin:
    default: op

commands:
  trap:
    description: Instantly activate a random trap.
  keepbag:
    description: Allows players to keep their inventory on death